// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfigGet() {
  return window['go']['app']['App']['ConfigGet']();
}

export function ConfigSet(arg1) {
  return window['go']['app']['App']['ConfigSet'](arg1);
}

export function DialogDirSelect() {
  return window['go']['app']['App']['DialogDirSelect']();
}

export function FileGetAllFileList(arg1) {
  return window['go']['app']['App']['FileGetAllFileList'](arg1);
}

export function FileGetCurrentPath() {
  return window['go']['app']['App']['FileGetCurrentPath']();
}

export function FileGetDesktopPath() {
  return window['go']['app']['App']['FileGetDesktopPath']();
}

export function FileHash(arg1) {
  return window['go']['app']['App']['FileHash'](arg1);
}

export function FileReadDir(arg1) {
  return window['go']['app']['App']['FileReadDir'](arg1);
}

export function FileReadFile(arg1) {
  return window['go']['app']['App']['FileReadFile'](arg1);
}

export function FileWriteFile(arg1, arg2) {
  return window['go']['app']['App']['FileWriteFile'](arg1, arg2);
}

export function HttpFetch(arg1) {
  return window['go']['app']['App']['HttpFetch'](arg1);
}

export function SysGetCpuPercent() {
  return window['go']['app']['App']['SysGetCpuPercent']();
}

export function SysGetMemPercent() {
  return window['go']['app']['App']['SysGetMemPercent']();
}
