// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {lib} from '../models';

export function ConfigGet():Promise<string>;

export function ConfigSet(arg1:string):void;

export function DialogDirSelect():Promise<string>;

export function FileGetAllFileList(arg1:string):Promise<Array<lib.FileItem>>;

export function FileGetCurrentPath():Promise<string>;

export function FileGetDesktopPath():Promise<string>;

export function FileHash(arg1:string):Promise<string>;

export function FileReadDir(arg1:string):Promise<Array<lib.FileItem>>;

export function FileReadFile(arg1:string):Promise<string>;

export function FileWriteFile(arg1:string,arg2:string):void;

export function HttpFetch(arg1:lib.HttpRequest):Promise<lib.HttpResponse>;

export function SysGetCpuPercent():Promise<number>;

export function SysGetMemPercent():Promise<number>;

export function SysRebuild():void;
