// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfigGet() {
  return window['go']['main']['App']['ConfigGet']();
}

export function ConfigSet(arg1) {
  return window['go']['main']['App']['ConfigSet'](arg1);
}

export function DialogDirSelect() {
  return window['go']['main']['App']['DialogDirSelect']();
}

export function FileGetAllFileList(arg1) {
  return window['go']['main']['App']['FileGetAllFileList'](arg1);
}

export function FileHash(arg1) {
  return window['go']['main']['App']['FileHash'](arg1);
}

export function FileReadDir(arg1) {
  return window['go']['main']['App']['FileReadDir'](arg1);
}

export function HttpFetch(arg1) {
  return window['go']['main']['App']['HttpFetch'](arg1);
}

export function SysGetCpuPercent() {
  return window['go']['main']['App']['SysGetCpuPercent']();
}

export function SysGetMemPercent() {
  return window['go']['main']['App']['SysGetMemPercent']();
}
