// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {lib} from '../models';

export function ConfigGet():Promise<string>;

export function ConfigSet(arg1:string):void;

export function HttpFetch(arg1:lib.HttpRequest):Promise<lib.HttpResponse>;
