// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfigSet(arg1) {
  return window['go']['main']['App']['ConfigSet'](arg1);
}

export function ConfigGet() {
  return window['go']['main']['App']['ConfigGet']();
}
